<?php
return array(

	'root'					=> '/',
	'host'					=> 'http://icms2-dev',
	'upload_root'			=> '/upload/',
	'upload_host'			=> 'http://icms2-dev/upload',
	'cache_root'			=> '/cache/',
	'is_site_on'			=> '1',
	'off_reason'			=> 'Идут технические работы',
	'sitename'				=> 'InstantCMS 2.0',
	'hometitle'				=> 'InstantCMS 2.0',
	'date_format'			=> 'd.m.Y',
	'date_format_js'		=> 'dd.mm.yy',
	'time_zone'				=> 'Europe/Moscow',
	'template'				=> 'default',
	'template_admin'		=> 'default',
	'template_mobile'		=> '',
	'template_tablet'		=> '',
	'db_host'				=> 'localhost',
	'db_base'				=> 'icms2_dev',
	'db_user'				=> 'root',
	'db_pass'				=> 'mystery',
	'db_prefix'				=> 'cms_',
	'db_engine'				=> 'MyISAM',
	'db_users_table'		=> 'cms_users',
	'language'				=> 'ru',
	'metakeys'				=> 'ключевые, слова, сайта',
	'metadesc'				=> 'Описание сайта',
	'ct_autoload'			=> 'frontpage',
	'ct_default'			=> 'content',
	'frontpage'				=> 'none',
	'debug'					=> '0',
	'emulate_lag'			=> '',
	'cache_enabled'			=> '0',
	'cache_method'			=> 'files',
	'cache_ttl'				=> '300',
	'cache_host'			=> 'localhost',
	'cache_port'			=> '11211',
	'min_html'				=> '0',
	'merge_css'				=> '0',
	'merge_js'				=> '0',
	'mail_transport'		=> 'mail',
	'mail_from'				=> 'noreply@example.com',
	'mail_from_name'		=> '',
	'mail_smtp_server'		=> 'smtp.example.com',
	'mail_smtp_port'		=> '25',
	'mail_smtp_auth'		=> '1',
	'mail_smtp_user'		=> 'user@example.com',
	'mail_smtp_pass'		=> '',
	'is_check_updates'		=> '1',
	'detect_ip_key'			=> 'REMOTE_ADDR',
	'allow_ips'				=> '',
	'default_editor'		=> 'redactor',
	'show_breadcrumbs'		=> '1',

);
