DROP TABLE IF EXISTS `{#}events`;
CREATE TABLE `{#}events` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `event` varchar(64) DEFAULT NULL COMMENT 'Событие',
  `listener` varchar(32) DEFAULT NULL COMMENT 'Слушатель (компонент)',
  `ordering` int(5) unsigned DEFAULT NULL COMMENT 'Порядковый номер ',
  `is_enabled` tinyint(1) unsigned DEFAULT '1' COMMENT 'Активность',
  PRIMARY KEY (`id`),
  KEY `hook` (`event`),
  KEY `listener` (`listener`),
  KEY `is_enabled` (`is_enabled`,`ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Привязка хуков к событиям';


INSERT INTO `{#}events` (`id`, `event`, `listener`, `ordering`, `is_enabled`) VALUES
(1, 'content_after_add_approve', 'activity', 14, 1),
(2, 'content_after_update_approve', 'activity', 18, 1),
(3, 'publish_delayed_content', 'activity', 53, 1),
(4, 'user_delete', 'activity', 65, 1),
(5, 'user_tab_info', 'activity', 91, 1),
(6, 'user_tab_show', 'activity', 94, 1),
(7, 'menu_admin', 'admin', 46, 1),
(8, 'user_login', 'admin', 74, 1),
(9, 'user_profile_update', 'auth', 87, 1),
(10, 'frontpage', 'auth', 39, 1),
(11, 'frontpage_types', 'auth', 41, 1),
(12, 'content_after_update', 'comments', 17, 1),
(13, 'admin_dashboard_block', 'comments', 2, 1),
(14, 'admin_dashboard_chart', 'comments', 5, 1),
(15, 'user_privacy_types', 'comments', 83, 1),
(16, 'user_login', 'comments', 75, 1),
(17, 'user_notify_types', 'comments', 78, 1),
(18, 'user_delete', 'comments', 64, 1),
(19, 'user_tab_info', 'comments', 90, 1),
(20, 'user_tab_show', 'comments', 93, 1),
(21, 'rss_content_controller_form', 'content', 57, 1),
(22, 'frontpage_types', 'content', 42, 1),
(23, 'ctype_after_update', 'frontpage', 34, 1),
(24, 'ctype_after_delete', 'frontpage', 33, 1),
(25, 'admin_dashboard_chart', 'groups', 6, 1),
(26, 'content_view_hidden', 'groups', 30, 1),
(27, 'rating_vote', 'groups', 54, 1),
(28, 'user_privacy_types', 'groups', 84, 1),
(29, 'user_profile_buttons', 'groups', 86, 1),
(30, 'user_notify_types', 'groups', 80, 1),
(31, 'user_delete', 'groups', 69, 1),
(32, 'user_tab_info', 'groups', 92, 1),
(33, 'user_tab_show', 'groups', 95, 1),
(34, 'menu_groups', 'groups', 48, 1),
(35, 'sitemap_sources', 'groups', 61, 1),
(36, 'sitemap_urls', 'groups', 62, 1),
(37, 'user_delete', 'images', 67, 1),
(38, 'admin_dashboard_chart', 'messages', 4, 1),
(39, 'menu_messages', 'messages', 49, 1),
(40, 'users_profile_view', 'messages', 63, 1),
(41, 'user_privacy_types', 'messages', 82, 1),
(42, 'user_delete', 'messages', 66, 1),
(43, 'user_notify_types', 'messages', 77, 1),
(44, 'admin_dashboard_block', 'moderation', 3, 1),
(45, 'content_after_trash_put', 'moderation', 16, 1),
(46, 'content_after_restore', 'moderation', 15, 1),
(47, 'content_before_delete', 'moderation', 26, 1),
(48, 'menu_moderation', 'moderation', 50, 1),
(49, 'content_albums_items_html', 'photos', 23, 1),
(50, 'fulltext_search', 'photos', 43, 1),
(51, 'admin_albums_ctype_menu', 'photos', 1, 1),
(52, 'content_albums_after_add', 'photos', 19, 1),
(53, 'content_albums_after_delete', 'photos', 20, 1),
(54, 'content_albums_item_html', 'photos', 24, 1),
(55, 'content_albums_before_item', 'photos', 21, 1),
(56, 'content_albums_before_list', 'photos', 22, 1),
(57, 'user_delete', 'photos', 70, 1),
(58, 'user_delete', 'rating', 72, 1),
(59, 'captcha_html', 'recaptcha', 12, 1),
(60, 'captcha_validate', 'recaptcha', 13, 1),
(61, 'ctype_basic_form', 'rss', 35, 1),
(62, 'ctype_before_add', 'rss', 36, 1),
(63, 'ctype_after_add', 'rss', 31, 1),
(64, 'ctype_before_edit', 'rss', 37, 1),
(65, 'ctype_before_update', 'rss', 38, 1),
(66, 'ctype_after_delete', 'rss', 32, 1),
(67, 'content_before_category', 'rss', 25, 1),
(68, 'content_before_profile', 'rss', 29, 1),
(69, 'photos_before_item', 'search', 52, 1),
(70, 'content_before_list', 'search', 28, 1),
(71, 'content_before_item', 'search', 27, 1),
(72, 'before_print_head', 'search', 11, 1),
(73, 'html_filter', 'typograph', 45, 1),
(74, 'admin_dashboard_chart', 'users', 9, 1),
(75, 'menu_users', 'users', 51, 1),
(76, 'rating_vote', 'users', 55, 1),
(77, 'user_notify_types', 'users', 79, 1),
(78, 'user_privacy_types', 'users', 81, 1),
(79, 'user_tab_info', 'users', 89, 1),
(80, 'auth_login', 'users', 10, 1),
(81, 'user_loaded', 'users', 73, 1),
(82, 'wall_permissions', 'users', 99, 1),
(83, 'wall_after_add', 'users', 97, 1),
(84, 'wall_after_delete', 'users', 98, 1),
(85, 'sitemap_sources', 'users', 60, 1),
(86, 'admin_dashboard_chart', 'wall', 8, 1),
(87, 'user_notify_types', 'wall', 76, 1),
(88, 'user_delete', 'wall', 68, 1),
(89, 'user_privacy_types', 'content', 85, 1),
(90, 'sitemap_sources', 'content', 59, 1),
(91, 'rss_feed_list', 'content', 58, 1),
(92, 'fulltext_search', 'content', 44, 1),
(93, 'rss_content_controller_after_update', 'content', 56, 1),
(94, 'frontpage', 'content', 40, 1),
(95, 'admin_dashboard_chart', 'content', 7, 1),
(96, 'menu_content', 'content', 47, 1),
(97, 'user_delete', 'content', 71, 1),
(98, 'user_tab_info', 'content', 88, 1),
(99, 'user_tab_show', 'content', 96, 1);
