tinymce.addI18n("ru", {
  "#": "#",
  "Accessibility": "Специальные возможности",
  "Accordion": "Аккордеон",
  "Accordion body...": "Тело аккордеона...",
  "Accordion summary...": "Аннотация аккордеона...",
  "Action": "Действие",
  "Activity": "Активность",
  "Address": "Адрес",
  "Advanced": "Дополнительные",
  "Align": "Выровнять",
  "Align center": "Выровнять по центру",
  "Align left": "Выровнять по левому краю",
  "Align right": "Выровнять по правому краю",
  "Alignment": "Выравнивание",
  "Alignment {0}": "Выравнивание {0}",
  "All": "Все",
  "Alternative description": "Альтернативное описание",
  "Alternative source": "Альтернативный источник",
  "Alternative source URL": "URL альтернативного источника",
  "Anchor": "Якорь",
  "Anchor...": "Якорь...",
  "Anchors": "Якоря",
  "Animals and Nature": "Животные и природа",
  "Arrows": "Стрелки",
  "B": "B",
  "Background color": "Цвет фона",
  "Background color {0}": "{0} цвет фона",
  "Black": "Черный",
  "Block": "Блок",
  "Block {0}": "Блок {0}",
  "Blockquote": "Блок цитирования",
  "Blocks": "Блоки",
  "Blue": "Синий",
  "Blue component": "Синяя компонента",
  "Body": "Тело",
  "Bold": "Жирный шрифт",
  "Border": "Граница",
  "Border color": "Цвет границы",
  "Border style": "Стиль рамки",
  "Border width": "Ширина рамки",
  "Bottom": "По низу",
  "Browse files": "Выбор файлов",
  "Browse for an image": "Выбор изображения",
  "Browse links": "Выбор ссылок",
  "Bullet list": "Маркированный список",
  "Cancel": "Отменить",
  "Caption": "Заголовок",
  "Cell": "Ячейка",
  "Cell padding": "Внутренний отступ ячейки",
  "Cell properties": "Параметры ячейки",
  "Cell spacing": "Внешний отступ ячейки",
  "Cell styles": "Стили ячейки",
  "Cell type": "Тип ячейки",
  "Center": "По центру",
  "Characters": "Символы",
  "Characters (no spaces)": "Символы (без пробелов)",
  "Circle": "Кружок",
  "Class": "Класс",
  "Clear formatting": "Удалить форматирование",
  "Close": "Закрыть",
  "Code": "Код",
  "Code sample...": "Пример кода...",
  "Code view": "Просмотр кода",
  "Color Picker": "Пипетка цвета",
  "Color swatch": "Образец цвета",
  "Cols": "Столбцы",
  "Column": "Столбец",
  "Column clipboard actions": "Действия с буфером обмена для столбца",
  "Column group": "Группа столбцов",
  "Column header": "Заголовок столбца",
  "Constrain proportions": "Ограничить пропорции",
  "Copy": "Копировать",
  "Copy column": "Копировать столбец",
  "Copy row": "Копировать строку",
  "Could not find the specified string.": "Заданная строка не найдена",
  "Could not load emojis": "Не получилось загрузить смайлики",
  "Count": "Подсчет",
  "Currency": "Валюта",
  "Current window": "Текущее окно",
  "Custom color": "Пользовательский цвет",
  "Custom...": "Настраиваемый...",
  "Cut": "Вырезать",
  "Cut column": "Вырезать столбец",
  "Cut row": "Вырезать строку",
  "Dark Blue": "Темно-синий",
  "Dark Gray": "Темно-серый",
  "Dark Green": "Темно-зеленый",
  "Dark Orange": "Темно-оранжевый",
  "Dark Purple": "Темно-фиолетовый",
  "Dark Red": "Темно-красный",
  "Dark Turquoise": "Темно-бирюзовый",
  "Dark Yellow": "Темно-желтый",
  "Dashed": "Черточками",
  "Date/time": "Дата/время",
  "Decrease indent": "Уменьшить отступ",
  "Default": "По умолчанию",
  "Delete accordion": "Удалить аккордеон",
  "Delete column": "Удалить столбец",
  "Delete row": "Удалить строку",
  "Delete table": "Удалить таблицу",
  "Dimensions": "Размеры",
  "Disc": "Точка",
  "Div": "Div",
  "Document": "Документ",
  "Dotted": "Точками",
  "Double": "Двойной",
  "Drop an image here": "Перетащите изображение сюда",
  "Dropped file type is not supported": "Тип файла не поддерживается",
  "Edit": "Редактировать",
  "Embed": "Встроенный код",
  "Emojis": "Смайлики",
  "Emojis...": "Смайлики...",
  "Error": "Ошибка",
  "Error: Form submit field collision.": "Ошибка: конфликт полей отправки формы.",
  "Error: No form element found.": "Ошибка: не найден элемент формы.",
  "Extended Latin": "Расширенная латынь",
  "Failed to initialize plugin: {0}": "Ошибка при инициализации плагина: {0}",
  "Failed to load plugin url: {0}": "Ошибка при загрузке URL плагина: {0}",
  "Failed to load plugin: {0} from url {1}": "Ошибка при загрузке плагина: {0} из URL {1}",
  "Failed to upload image: {0}": "Ошибка при передаче изображения: {0}",
  "File": "Файл",
  "Find": "Найти",
  "Find (if searchreplace plugin activated)": "Найти (если плагин searchreplace активирован)",
  "Find and Replace": "Найти и Заменить",
  "Find and replace...": "Найти и заменить...",
  "Find in selection": "Найти в выделенном",
  "Find whole words only": "Найти только целые слова",
  "Flags": "Флаги",
  "Focus to contextual toolbar": "Фокус на контекстной панели инструментов",
  "Focus to element path": "Фокус на элементе пути",
  "Focus to menubar": "Фокус на панели меню",
  "Focus to toolbar": "Фокус на панели инструментов",
  "Font": "Шрифт",
  "Font size {0}": "Размер шрифта {0}",
  "Font sizes": "Размер шрифта",
  "Font {0}": "Шрифт {0}",
  "Fonts": "Шрифты",
  "Food and Drink": "Еда и напитки",
  "Footer": "Нижний колонтитул",
  "Format": "Формат",
  "Format {0}": "Формат {0}",
  "Formats": "Форматы",
  "Fullscreen": "Полный экран",
  "G": "G",
  "General": "Общие",
  "Gray": "Серый",
  "Green": "Зеленый",
  "Green component": "Зеленая компонента",
  "Groove": "Паз",
  "Handy Shortcuts": "Горячие клавиши",
  "Header": "Верхний колонтитул",
  "Header cell": "Ячейка верхнего колонтитула",
  "Heading 1": "Заголовок 1",
  "Heading 2": "Заголовок 2",
  "Heading 3": "Заголовок 3",
  "Heading 4": "Заголовок 4",
  "Heading 5": "Заголовок 5",
  "Heading 6": "Заголовок 6",
  "Headings": "Заголовки",
  "Height": "Высота",
  "Help": "Справка",
  "Hex color code": "HEX-код цвета",
  "Hidden": "Скрытый",
  "Horizontal align": "Горизонтальное выравнивание",
  "Horizontal line": "Горизонтальная линия",
  "Horizontal space": "Интервал по горизонтали",
  "ID": "ID",
  "ID should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "ID должен начинаться с буквы и содержать только буквы, цифры, черточку, точку, запятую или знак подчеркивания.",
  "Image is decorative": "Декоративное изображение",
  "Image list": "Список изображений",
  "Image title": "Название изображения",
  "Image...": "Изображение...",
  "ImageProxy HTTP error: Could not find Image Proxy": "Ошибка HTTP ImageProxy: не удалось найти Image Proxy",
  "ImageProxy HTTP error: Incorrect Image Proxy URL": "Ошибка HTTP ImageProxy: неверный URL-адрес Image Proxy",
  "ImageProxy HTTP error: Rejected request": "Ошибка HTTP ImageProxy: запрос отклонен",
  "ImageProxy HTTP error: Unknown ImageProxy error": "Ошибка HTTP ImageProxy: неизвестная ошибка ImageProxy",
  "Increase indent": "Увеличить отступ",
  "Inline": "Встроенный",
  "Insert": "Вставить",
  "Insert Template": "Вставить шаблон",
  "Insert accordion": "Вставить аккордеон",
  "Insert column after": "Добавить пустой столбец справа",
  "Insert column before": "Добавить пустой столбец слева",
  "Insert date/time": "Вставить дату/время",
  "Insert image": "Вставить изображение",
  "Insert link (if link plugin activated)": "Вставить ссылку (если плагин link активирован)",
  "Insert row after": "Вставить пустую строку снизу",
  "Insert row before": "Вставить пустую строку сверху",
  "Insert table": "Вставить таблицу",
  "Insert template...": "Вставить шаблон...",
  "Insert video": "Вставить видео",
  "Insert/Edit code sample": "Добавить/Изменить пример кода",
  "Insert/edit image": "Вставить/изменить изображение",
  "Insert/edit link": "Вставить/редактировать ссылку",
  "Insert/edit media": "Вставить/редактировать мультимедиа",
  "Insert/edit video": "Вставить/редактировать видео",
  "Inset": "Вставка",
  "Invalid hex color code: {0}": "Неверный HEX-код цвета: {0}",
  "Invalid input": "Неверное значение",
  "Italic": "Курсив",
  "Justify": "Выровнять текст по ширине",
  "Keyboard Navigation": "Управление с помощью клавиатуры",
  "Language": "Язык",
  "Learn more...": "Узнать больше...",
  "Left": "По левому краю",
  "Left to right": "Слева направо",
  "Light Blue": "Светло-синий",
  "Light Gray": "Светло-серый",
  "Light Green": "Светло-зеленый",
  "Light Purple": "Светло-фиолетовый",
  "Light Red": "Светло-красный",
  "Light Yellow": "Светло-желтый",
  "Line height": "Высота строки",
  "Link list": "Список ссылок",
  "Link...": "Ссылка...",
  "List Properties": "Список свойств",
  "List properties...": "Список свойств...",
  "Loading emojis...": "Загрузка смайликов...",
  "Loading...": "Загрузка...",
  "Lower Alpha": "Строчные латинские",
  "Lower Greek": "Строчные греческие",
  "Lower Roman": "Строчные римские",
  "Match case": "С учетом регистра",
  "Mathematical": "Математические",
  "Media poster (Image URL)": "Постер мультимедиа (URL изображения)",
  "Media...": "Мультимедиа...",
  "Medium Blue": "Средний синий",
  "Medium Gray": "Умеренно серый",
  "Medium Purple": "Умеренно пурпурный",
  "Merge cells": "Объединить ячейки",
  "Middle": "По середине",
  "Midnight Blue": "Черно-синий",
  "More...": "Больше...",
  "Name": "Название/Имя",
  "Navy Blue": "Темно-синий",
  "New document": "Новый документ",
  "New window": "Новое окно",
  "Next": "Продолжить",
  "No": "Нет",
  "No alignment": "Выравнивание не задано",
  "No color": "Без цвета",
  "Nonbreaking space": "Неразрывный пробел",
  "None": "Нет",
  "Numbered list": "Нумерованный список",
  "OR": "ИЛИ",
  "Objects": "Объекты",
  "Ok": "OK",
  "Open help dialog": "Открыть справку",
  "Open link": "Перейти по ссылке",
  "Open link in...": "Открыть ссылку в...",
  "Open popup menu for split buttons": "Открыть всплывающее меню для разделения кнопок",
  "Orange": "Оранжевый",
  "Outset": "Вырезка",
  "Page break": "Разрыв страницы",
  "Paragraph": "Абзац",
  "Paste": "Вставить",
  "Paste as text": "Вставить как текст",
  "Paste column after": "Вставить столбец справа",
  "Paste column before": "Вставить столбец слева",
  "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Вставка осуществляется в виде простого текста, пока не отключить данную опцию.",
  "Paste or type a link": "Введите или вставьте ссылку",
  "Paste row after": "Вставить строку снизу",
  "Paste row before": "Вставить строку сверху",
  "Paste your embed code below:": "Вставьте встроенный код ниже:",
  "People": "Люди",
  "Plugins": "Плагины",
  "Plugins installed ({0}):": "Установленные плагины ({0}):",
  "Powered by {0}": "Под управлением {0}",
  "Pre": "Pre",
  "Preferences": "Предпочтения",
  "Preformatted": "Предварительно форматированный",
  "Premium plugins:": "Премиум плагины:",
  "Press the Up and Down arrow keys to resize the editor.": "Нажимайте клавиши со стрелками вверх и вниз, чтобы изменить размер редактора.",
  "Press the arrow keys to resize the editor.": "Нажимайте клавиши со стрелками, чтобы изменить размер редактора.",
  "Press {0} for help": "Нажмите {0} для получения справки",
  "Preview": "Предварительный просмотр",
  "Previous": "Предыдущий",
  "Print": "Печать",
  "Print...": "Напечатать...",
  "Purple": "Розовый",
  "Quotations": "Цитаты",
  "R": "R",
  "Range 0 to 255": "Диапазон от 0 до 255",
  "Red": "Красный",
  "Red component": "Красная компонента",
  "Redo": "Redo",
  "Remove": "Удалить",
  "Remove color": "Удалить цвет",
  "Remove link": "Удалить ссылку",
  "Replace": "Заменить",
  "Replace all": "Заменить все",
  "Replace with": "Заменить на",
  "Resize": "Изменить размер",
  "Restore last draft": "Восстановить последний черновик",
  "Reveal or hide additional toolbar items": "Отображение или скрытие дополнительных элементов панели инструментов",
  "Rich Text Area": "Поле форматированного текста",
  "Rich Text Area. Press ALT-0 for help.": "Поле форматированного текста. Нажмите ALT-0, чтобы открыть справку.",
  "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Поле форматированного текста. Нажмите ALT-F9, чтобы открыть меню, ALT-F10, чтобы открыть панель инструментов, ALT-0, чтобы открыть справку.",
  "Ridge": "Шип",
  "Right": "По правому краю",
  "Right to left": "Справа налево",
  "Row": "Строка",
  "Row clipboard actions": "Действия с буфером обмена для строки",
  "Row group": "Группа строк",
  "Row header": "Заголовок строки",
  "Row properties": "Параметры строки",
  "Row type": "Тип строки",
  "Rows": "Строки",
  "Save": "Сохранить",
  "Save (if save plugin activated)": "Сохранить (если плагин save активирован)",
  "Scope": "Область действия",
  "Search": "Поиск",
  "Select all": "Выделить все",
  "Select...": "Выбрать...",
  "Selection": "Выбор",
  "Shortcut": "Быстрая клавиша",
  "Show blocks": "Показывать блоки",
  "Show caption": "Показать подпись",
  "Show invisible characters": "Показывать невидимые символы",
  "Size": "Размер",
  "Solid": "Сплошной",
  "Source": "Исходный объект",
  "Source code": "Исходный код",
  "Special Character": "Специальный символ",
  "Special character...": "Спец. символы...",
  "Split cell": "Разбить ячейку",
  "Square": "Квадрат",
  "Start list at number": "Начать нумерацию с",
  "Strikethrough": "Зачеркивание",
  "Style": "Стиль",
  "Subscript": "Подстрочный",
  "Superscript": "Надстрочный",
  "Switch to or from fullscreen mode": "Переключить полноэкранный режим",
  "Symbols": "Символы",
  "System Font": "Системный шрифт",
  "Table": "Таблица",
  "Table caption": "Заголовок таблицы",
  "Table properties": "Свойства таблицы",
  "Table styles": "Стили таблицы",
  "Template": "Шаблон",
  "Templates": "Шаблоны",
  "Text": "Текст",
  "Text color": "Цвет текста",
  "Text color {0}": "{0} цвет текста",
  "Text to display": "Отображаемый текст",
  "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Введенный вами URL-адрес, по-видимому, является адресом электронной почты. Хотите ли вы добавить необходимый префикс mailto:?",
  "The URL you entered seems to be an external link. Do you want to add the required http:// prefix?": "Введенный вами URL-адрес, по-видимому, является внешней ссылкой. Хотите ли вы добавить необходимый префикс http://?",
  "The URL you entered seems to be an external link. Do you want to add the required https:// prefix?": "Введенный вами URL-адрес, по-видимому, является внешней ссылкой. Хотите добавить необходимый префикс https://?",
  "Title": "Заголовок",
  "To open the popup, press Shift+Enter": "Чтобы открыть всплывающее окно, нажмите Shift+Enter",
  "Toggle accordion": "Переключение аккордеона",
  "Tools": "Инструменты",
  "Top": "По верху",
  "Travel and Places": "Путешествия и места",
  "Turquoise": "Бирюзовый",
  "Underline": "Подчеркивание",
  "Undo": "Undo",
  "Upload": "Передать",
  "Uploading image": "Загрузка картинки",
  "Upper Alpha": "Заглавные латинские",
  "Upper Roman": "Прописные римские",
  "Url": "URL-адрес",
  "User Defined": "Определяемые пользователем",
  "Valid": "Допустимый",
  "Version": "Версия",
  "Vertical align": "Вертикальное выравнивание",
  "Vertical space": "Интервал по вертикали",
  "View": "Вид",
  "Visual aids": "Визуальные подсказки",
  "Warn": "Предупреждение",
  "White": "Белый",
  "Width": "Ширина",
  "Word count": "Количество слов",
  "Words": "Слова",
  "Words: {0}": "Слов: {0}",
  "Yellow": "Желтый",
  "Yes": "Да",
  "You are using {0}": "Вы используете {0}",
  "You have unsaved changes are you sure you want to navigate away?": "У вас есть несохраненные изменения. Вы уверены, что хотите выйти?",
  "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "Ваш браузер не поддерживает прямой доступ к буферу обмена. Используйте следующие сочетания клавиш: Ctrl+X/C/V.",
  "alignment": "выравнивание",
  "austral sign": "Символ аустрала",
  "cedi sign": "Символ седи",
  "colon sign": "Двоеточие",
  "cruzeiro sign": "Символ крузейро",
  "currency sign": "Символ валюты",
  "dollar sign": "Символ доллара",
  "dong sign": "Символ донга",
  "drachma sign": "Символ драхмы",
  "euro-currency sign": "Символ евро",
  "example": "пример",
  "formatting": "форматирование",
  "french franc sign": "Символ французского франка",
  "german penny symbol": "символ пфеннига",
  "guarani sign": "Символ гуарани",
  "history": "история",
  "hryvnia sign": "Символ гривни",
  "indentation": "отступ",
  "indian rupee sign": "Символ индийской рупии",
  "kip sign": "Символ кипы",
  "lira sign": "Символ лиры",
  "livre tournois sign": "Символ ливры",
  "manat sign": "Символ маната",
  "mill sign": "Символ десятой части цента",
  "naira sign": "Символ найры",
  "new sheqel sign": "Символ шекеля",
  "nordic mark sign": "Символ марки",
  "peseta sign": "Символ песеты",
  "peso sign": "Символ песо",
  "ruble sign": "Символ рубля",
  "rupee sign": "Символ рупии",
  "spesmilo sign": "Символ спесмило",
  "styles": "стили",
  "tenge sign": "Символ теньге",
  "tugrik sign": "Символ тугрика",
  "turkish lira sign": "Символ турецкой лиры",
  "won sign": "Символ воны",
  "yen character": "символ иены",
  "yen/yuan character variant one": "символ иены/юаня, вариант 1",
  "yuan character": "символ юаня",
  "yuan character, in hong kong and taiwan": "Символ юаня, Гонконг и Тайвань",
  "{0} characters": "{0} символ.",
  "{0} columns, {1} rows": "{0} столбцов, {1} строк",
  "{0} words": "{0} слов",
  "Insert smiles": "Вставить смайлы",
  "Add spoiler": "Вставить спойлер",
  "Remove spoiler": "Удалить спойлер"
});
